CREATE DATABASE IF NOT EXISTS `kviz` DEFAULT CHARACTER SET latin1 ;
USE `kviz` ;

CREATE TABLE IF NOT EXISTS admin (
    name VARCHAR(50) PRIMARY KEY NOT NULL,
    password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS user (
    name VARCHAR(50) PRIMARY KEY NOT NULL,
    password VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS questionAndAnswer (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    question VARCHAR(100) NOT NULL,
    offeredAnswers VARCHAR(100) NOT NULL,
    correctAnswer VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS score (
    ID INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    nameOfUser VARCHAR(50) NOT NULL,
    score INTEGER NOT NULL,
    date DATETIME NOT NULL
);
    
